[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "drl-analyzer"
version = "1.0.0"
description = "Deep Reinforcement Learning Experiment Analyzer"
authors = [
    {name="yyJ"}
]
requires-python = ">=3.10"

dependencies = [
    "numpy>=1.24",
    "pandas>=2.0",
    "matplotlib>=3.8",
    "openpyxl>=3.1",
    "PyYAML>=6.0",
    "wandb>=0.18"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]